# Generated by Django 5.1.9 on 2025-05-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='company',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
