# Generated by Django 5.1.9 on 2025-05-29 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_status_duration_days_comment_companystatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companystatushistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
