# Generated by Django 5.1.9 on 2025-05-29 06:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(choices=[('KST', 'Костанай'), ('AKM', 'Акмола'), ('PAV', 'Павлодар'), ('KAR', 'Караганда'), ('VKO', 'ВКО'), ('SKO', 'СКО')], default='KST', max_length=3, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('KST', 'Костанай'), ('AKM', 'Акмола'), ('PAV', 'Павлодар'), ('KAR', 'Караганда'), ('VKO', 'ВКО'), ('SKO', 'СКО')], default='KST', max_length=3, verbose_name='Регион'),
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='companystatushistory',
            options={'ordering': ['-changed_at'], 'verbose_name_plural': 'История статусов'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='company',
            name='position',
            field=models.IntegerField(default=0, help_text='Порядок внутри одного статуса на доске', verbose_name='Позиция в колонке'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status', verbose_name='Текущий статус'),
        ),
        migrations.AlterField(
            model_name='companystatushistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Когда был установлен этот статус', verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='companystatushistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companystatushistory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='status',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Рекомендованное количество дней в этом статусе', verbose_name='Рекомендуемое время (дней)'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название статуса'),
        ),
        migrations.AlterField(
            model_name='status',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше — тем левее на доске', verbose_name='Порядок отображения'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
