# Generated by Django 5.1.9 on 2025-05-29 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_company_region_alter_profile_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['position'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='companystatushistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Запись истории статусов', 'verbose_name_plural': 'История статусов'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(choices=[('KST', 'Костанай'), ('AKM', 'Акмола'), ('PAV', 'Павлодар'), ('KAR', 'Караганда'), ('VKO', 'ВКО'), ('SKO', 'СКО')], default='KST', help_text='Географический регион компании', max_length=3, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.status', verbose_name='Текущий статус'),
        ),
        migrations.AlterField(
            model_name='companystatushistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Когда был установлен этот статус', verbose_name='Дата и время смены'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('KST', 'Костанай'), ('AKM', 'Акмола'), ('PAV', 'Павлодар'), ('KAR', 'Караганда'), ('VKO', 'ВКО'), ('SKO', 'СКО')], default='KST', help_text='Географический регион пользователя', max_length=3, verbose_name='Регион пользователя'),
        ),
    ]
