# Generated by Django 5.1.9 on 2025-05-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comment_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
